#!/bin/bash -e
export PYTHONPATH=/rpi/lex/python
case $1 in
    run)
        /venv/bin/python -m run
        ;;
    run_no_snowboy)
        /venv/bin/python -m run_no_snowboy
        ;;
    help|--help)
        cat <<EOF
libbypi docker container

USAGE:
    docker run \\
        -e AWS_DEFAULT_REGION=eu-west-1 \\
        -e AWS_ACCESS_KEY_ID=... \\
        -e AWS_SECRET_ACCESS_KEY=... \\
        --device /dev/snd --privileged \\
        [-i -t] libbypi MODE

where MODE is one of
  - run
  - run_no_snowboy
  - help (prints this message)
  - shell (requires -i -t to be usable)

EOF
        ;;
    shell)
        exec /bin/bash
        ;;
    *)
        echo "unexpected arguments (try help instead)" 1>&2
        exit 1
        ;;
esac
